package com.ids.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Packet — data transfer object for one captured network packet.
 *
 * This object is created by TrafficSimulator, serialized to JSON by Jackson,
 * and pushed to the browser dashboard via WebSocket every 700ms.
 *
 * In a real IDS, these fields would be extracted from raw pcap data using
 * a library like Pcap4J. Here they are generated by the simulation engine
 * with realistic values matching CIC-IoT 2023 dataset characteristics.
 *
 * Lombok annotations used:
 *   @Data              — generates getters, setters, toString, equals, hashCode
 *   @Builder           — enables Packet.builder().field(value)...build()
 *   @NoArgsConstructor — required by Jackson for JSON deserialization
 *   @AllArgsConstructor — required by @Builder to work properly
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Packet {

    /** Short 8-char UUID — used as unique key in frontend table rows */
    private String id;

    /** Capture timestamp formatted as HH:mm:ss.SSS for display */
    private String timestamp;

    /** IP address of the packet sender (IoT device or external attacker) */
    private String sourceIp;

    /** IP address of the packet receiver (IoT device or IDS server) */
    private String destIp;

    /**
     * Network protocol used by this packet.
     * Values: TCP, UDP, ICMP, ARP
     * Note: ARP is Layer 2, does not use ports (port will be 0)
     */
    private String protocol;

    /** Destination port number — 0 for ARP and ICMP which have no ports */
    private int port;

    /** Packet payload size in bytes */
    private int packetSize;

    /**
     * Attack classification — output of the AI detection engine.
     *
     * BENIGN     — normal IoT sensor telemetry (MQTT on 1883, CoAP on 5683)
     * UDP_FLOOD  — volumetric UDP denial-of-service targeting ESP32-CAM
     * DATA_SNIFF — unauthorized capture of DHT11 sensor data via Telnet
     * ARP_SPOOF  — ARP table poisoning to hijack ESP32 gateway traffic
     * PORT_SCAN  — TCP SYN reconnaissance to find open services on IoT subnet
     */
    private String attackType;

    /**
     * OSI model layer at which the attack was detected.
     * Demonstrates the "multi-layer" aspect of this IDS project:
     *
     *   NONE — no attack (benign traffic, no OSI layer flagged)
     *   L2   — Data Link layer (ARP spoofing attacks)
     *   L4   — Transport layer (UDP flood, port scan via TCP/UDP)
     *   L7   — Application layer (data sniffing via Telnet protocol)
     */
    private String attackLayer;

    /**
     * XGBoost model confidence score.
     * Range: 0.0 (very uncertain) to 1.0 (very certain)
     * Displayed as a percentage bar in the packet table.
     */
    private double confidence;

    /**
     * Computed threat severity score for the threat gauge.
     * Range: 0 (safe/benign) to 100 (critical attack)
     * Feeds the real-time arc gauge on the dashboard.
     */
    private int severityScore;

    /** Device ID of the IoT node associated with this packet */
    private String sourceNode;

    /**
     * Actual measured packet rate from the ESP32 sniffer (packets per second).
     * Used by the dashboard chart to show the real hardware-observed PPS,
     * not just the count of WebSocket messages received.
     */
    private int pktRate;

    /**
     * Quick boolean flag — true if any attack was detected.
     * Used by frontend to apply red highlight styling to table rows.
     */
    private boolean attack;
}
